CREATE TABLE IF NOT EXISTS CATALOG
(
    CATALOG_ID   SERIAL PRIMARY KEY,
    NAME         VARCHAR(100) NOT NULL,
    DESCRIPTION  VARCHAR(256),
    CREATED_DATE TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCT
(
    PRODUCT_ID   SERIAL PRIMARY KEY,
    NAME         VARCHAR(100),
    DESCRIPTION  VARCHAR(256),
    SKU          VARCHAR(100) not null,
    CREATED_DATE TIMESTAMP,
    CONSTRAINT UNIQUE_SKU UNIQUE (SKU)
);

CREATE TABLE IF NOT EXISTS CATALOG_PRODUCT
(
    CATALOG_ID   SERIAL,
    PRODUCT_ID   SERIAL,
    CONSTRAINT CATALOG_PRODUCT_PK PRIMARY KEY (CATALOG_ID,PRODUCT_ID),
    CONSTRAINT PRODUCT_ID_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE,
    CONSTRAINT CATALOG_ID_FK FOREIGN KEY (CATALOG_ID) REFERENCES CATALOG(CATALOG_ID) ON DELETE CASCADE
);